name: "Podcast Generator"
description: "Generates a feed for a podcast from a YAML file"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "git-branch"
  color: "red"

inputs:
  feed_url:
    description: "URL of the podcast feed"
    required: true
